### ISSUE TITLE
How to setting output file dir?

### ISSUE THREAD

**Issue by tommypratama** [Stephen-X/Lynda-Video-Downloader#2]
hello, how do I set the output location for the downloaded file?

**Comment by Stephen-X** [comment]
You're free to update the script to add a [`paths`](https://github.com/yt-dlp/yt-dlp/blob/2301b5c1b77a65abbb46b72f91e1e4666fd5d985/yt_dlp/YoutubeDL.py#L241) parameter to `ydl_opts`. By default all files are downloaded to the same directory as `down.py`.

Edit: I updated the script to make better use of `yt-dlp`, among the new changes a way to customize output path. Feel free to pull the latest changes.
